Config files
mahdy-nasr/dorraqapp pull request #3
Opened 2023-11-30 11:39 UTC by Ammar22-star0

Fix library conflicts && Add database URL

2023-12-02 14:18 UTC, mahdy-nasr commented on Backend/.husky/pre-commit
> +npm test
I don't think running the test as part of the git "pre-commit" hook is good idea. It will slow down the commit process considerably. 
 Usually pre-commit hooks are used to format the code file but not to run long-lasting process. 
 
 NPM test is more suitable to CI phase in github.

2023-12-03 16:03 UTC, mahdy-nasr requested changes

2023-12-03 16:03 UTC, mahdy-nasr commented on Backend/.husky/pre-commit
> +npm test
@Ammar22-star0

2023-12-03 17:21 UTC, Ammar-Alesrawi commented on Backend/.husky/pre-commit
> +npm test
Do I delete a pre-commit file or I need to do other modifications?

2023-12-04 08:29 UTC, Ammar-Alesrawi commented on Backend/.husky/pre-commit
> +npm test
The file has been deleted 
@mahdy-nasr

2023-12-04 18:09 UTC, mahdy-nasr approved these changes

2023-12-04 18:11 UTC, merged